### ISSUE TITLE
[Issue] 0.4.3 regresses docker hub credentials helper

### ISSUE THREAD

**Issue by francisferrell** [regclient/regclient#245]
### Current Behavior

```
regctl image copy registry.gitlab.com/francisferrell/http-ok:750c36df francisferrell/http-ok:test
WARN[0000] Failed to handle auth request                 Err=unauthorized URL="https://registry-1.docker.io/v2/francisferrell/http-ok/manifests/test"
WARN[0000] Failed to push manifest                       err="failed to put manifest docker.io/francisferrell/http-ok:test: unauthorized" target="francisferrell/http-ok:test"
failed to put manifest docker.io/francisferrell/http-ok:test: unauthorized
```

### Expected Behavior

copy command succeeds as there are credentials helpers in effect for both my gitlab registry and my docker hub registry

### Steps To Reproduce

1. In francisferrell/ci with DIND in effect
2. With `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN` set in the env
3. Run `regctl image copy some-source-image some-docker-hub-image`

### Version

```text
{
  "VCSRef": "b0ac3e9413b1079c8b14df5c201a2a2129d9d9e1",
  "VCSTag": "v0.4.3"
}
```

### Environment

- Running as binary or container: binary (the result of `make bin/regctl plugin-user` from a git clone)
- Host platform: docker-in-docker. confirmed on Linux x86 and Mac ARM
- Registry description: gitlab (source image) docker hub (destination image)

### Anything else

I've performed a git bisect and it's 5dad8a9c5b536a5d999c7bb5a69703307474f7c0 that introduced the regression.

```
root@9a2842fb9c7d:/# regctl version
{
  "VCSRef": "ff7250696d4e747fb6f28a175d8b1bf15792a878",
  "VCSTag": ""
}
root@9a2842fb9c7d:/# regctl image copy registry.gitlab.com/francisferrell/http-ok:750c36df francisferrell/http-ok:test
root@9a2842fb9c7d:/# echo $?
0
```

```
root@a587f17b70ce:/# regctl version
{
  "VCSRef": "5dad8a9c5b536a5d999c7bb5a69703307474f7c0",
  "VCSTag": ""
}
root@a587f17b70ce:/# regctl image copy registry.gitlab.com/francisferrell/http-ok:750c36df francisferrell/http-ok:test
WARN[0000] Failed to handle auth request                 Err=unauthorized URL="https://registry-1.docker.io/v2/francisferrell/http-ok/manifests/test"
WARN[0000] Failed to push manifest                       err="failed to put manifest docker.io/francisferrell/http-ok:test: unauthorized" target="francisferrell/http-ok:test"
failed to put manifest docker.io/francisferrell/http-ok:test: unauthorized
```

I don't know enough about regctl to comment on whether or not the issue affects both the gitlab and the docker hub credentials helper or just the docker hub credentials helper. The runtime environment is configured with a credentials helper for both.

**Comment by francisferrell** [comment]
Since the commit in question sounds like it has to do with parsing the docker config file, here's the contents of the config file in the failing environment:

```
cat ~/.docker/config.json
{
  "credHelpers": {
    "https://index.docker.io/v1/": "docker-hub",
    "registry.gitlab.com/francisferrell/http-ok": "gitlab"
  }
}
```

**Comment by francisferrell** [comment]
It's also worth noting that the credentials helpers are my own implementation. They are quick and dirty little bash scripts and they may not implement the complete and correct spec of a credential helper.

They can be found here: https://gitlab.com/francisferrell/ci/-/tree/main/rootfs/usr/local/bin

**Comment by sudo-bmitch** [comment]
> Since the commit in question sounds like it has to do with parsing the docker config file, here's the contents of the config file in the failing environment:
> 
> ```
> cat ~/.docker/config.json
> {
>   "credHelpers": {
>     "https://index.docker.io/v1/": "docker-hub",
>     "registry.gitlab.com/francisferrell/http-ok": "gitlab"
>   }
> }
> ```

That is a bit unexpected. I thought the first field would only contain a registry name. E.g.

```jsonc
  "credHelpers": {
    "https://index.docker.io/v1/": "docker-hub",
    "registry.gitlab.com": "gitlab"
  }
```

(The index.docker.io should be treated as a special use case, but I need to add more test cases.) I'll do some digging in the docker/cli code to see how they handle that case and make sure to mirror it.

**Comment by sudo-bmitch** [comment]
For a short term workaround, the following should get you back up:

```shell
regctl registry set --cred-helper docker-credential-docker-hub docker.io
regctl registry set --cred-helper docker-credential-gitlab registry.gitlab.com
```

**Comment by sudo-bmitch** [comment]
@francisferrell Thanks for the explanation. I think you want `CI_REGISTRY=registry.gitlab.com` and `CI_REGISTRY_IMAGE=registry.gitlab.com/francisferrell/http-ok` on the GitLab side. The `docker login` may be stripping that path (I probably should too, along with throwing a warning).

The credential helper parsing of the Gitlab line might be a red herring. If there's a `docker login` elsewhere, or the repo allows read access from your runner, it might be working even without the credHelper line. The parsing of the Docker Hub `index` is a bug in my code. I'll get a fix for that pushed out after work today.

**Comment by francisferrell** [comment]
> I think you want CI_REGISTRY=...

I don't have control over these. They are built-ins.

> The credential helper parsing of the Gitlab line might be a red herring. If there's a docker login elsewhere, or the repo allows read access from your runner ...

The credentials helper is in place to avoid the need for a docker login, so there is none.

I can craft a test that will verify the interaction between regctl and the gitlab registry in isolation, without docker hub in play, if you'd like.

> I'll get a fix for that pushed out after work today.

Thanks so much! I'll be happy to test any fixes you propose.

**Comment by sudo-bmitch** [comment]
The anonymous read access makes a lot of sense. I couldn't find anything in Docker's parsing of the file that would strip the path suffix, only the `https://` scheme. The parsing of Docker's `index` entry was definitely broken in v0.4.3 which should be fixed by #246. If it gives you any trouble, let me know and we can reopen this. Thanks for the report!

**Comment by francisferrell** [comment]
Thanks for the quick response. I love the regctl tool for shuffling multi-arch images around.

Unfortunately, that didn't seem to fix the issue. Both cred helpers still fail in the same way.

```
root@81e3255df52f:/# regctl tag ls -v debug francisferrell/http-ok
DEBU[0000] Loading docker config                         api= blobChunk=0 blobMax=0 helper=docker-credential-docker-hub hostname=registry-1.docker.io mirrors="[]" name=docker.io pathPrefix= repoAuth=false tls=enabled user=
DEBU[0000] Loading docker config                         api= blobChunk=0 blobMax=0 helper=docker-credential-gitlab hostname=registry.gitlab.com/francisferrell/http-ok mirrors="[]" name=registry.gitlab.com/francisferrell/http-ok pathPrefix= repoAuth=false tls=enabled user=
DEBU[0000] regclient initialized                         VCSRef=1f2c0918649a4ec557741ef572ee1b6cd2b3c8e8 VCSTag=
DEBU[0000] Listing tags                                  host=docker.io repository=francisferrell/http-ok
DEBU[0000] http req                                      method=GET url="https://registry-1.docker.io/v2/francisferrell/http-ok/tags/list" withAuth=false
DEBU[0000] Auth request parsed                           challenge="[{bearer map[realm:https://auth.docker.io/token scope:repository:francisferrell/http-ok:pull service:registry.docker.io]}]"
DEBU[0000] http req                                      method=GET url="https://registry-1.docker.io/v2/francisferrell/http-ok/tags/list" withAuth=true
latest

root@81e3255df52f:/# regctl image copy francisferrell/http-ok:latest francisferrell/http-ok:test
WARN[0000] Failed to handle auth request                 Err=unauthorized URL="https://registry-1.docker.io/v2/francisferrell/http-ok/manifests/test"
WARN[0000] Failed to push manifest                       err="failed to put manifest docker.io/francisferrell/http-ok:test: unauthorized" target="francisferrell/http-ok:test"
failed to put manifest docker.io/francisferrell/http-ok:test: unauthorized
```

**Comment by francisferrell** [comment]
Let me know if I can do anything else to help debug.

**Comment by sudo-bmitch** [comment]
Shucks, and I suspect the issue is now that I'm calling the helper with the normalized name. I may need to track another field for this to know what name to call the helper with. I'll get that updated tomorrow.

With v0.4.2, were you able to use the credential helper to write to Gitlab, or was that always broken and only the anonymous read worked?

**Comment by francisferrell** [comment]
Oh, interesting; it did not work!

```
root@f9ea734b4de4:/# regctl version
{
  "VCSRef": "c8125cd51a02bbff6a002f77eb8458b7a7753b63",
  "VCSTag": "v0.4.2"
}

root@f9ea734b4de4:/# regctl tag ls -v debug registry.gitlab.com/francisferrell/http-ok
DEBU[0000] Loading docker cred                           host=registry-1.docker.io name=docker.io pass-set=true tls=enabled token-set=false user=francisferrell
DEBU[0000] Loading docker cred                           host=registry.gitlab.com/francisferrell/http-ok name=registry.gitlab.com/francisferrell/http-ok pass-set=true tls=enabled token-set=false user=francisferrell@gmail.com
DEBU[0000] regclient initialized
DEBU[0000] Listing tags                                  host=registry.gitlab.com repository=francisferrell/http-ok
DEBU[0000] http req                                      method=GET url="https://registry.gitlab.com/v2/francisferrell/http-ok/tags/list" withAuth=false
DEBU[0000] Auth request parsed                           challenge="[{bearer map[realm:https://gitlab.com/jwt/auth scope:repository:francisferrell/http-ok:pull service:container_registry]}]"
DEBU[0000] http req                                      method=GET url="https://registry.gitlab.com/v2/francisferrell/http-ok/tags/list" withAuth=true
750c36df

root@f9ea734b4de4:/# regctl image copy registry.gitlab.com/francisferrell/http-ok:750c36df registry.gitlab.com/francisferrell/http-ok:test
WARN[0000] Failed to handle auth request                 Err=unauthorized URL="https://registry.gitlab.com/v2/francisferrell/http-ok/manifests/test"
WARN[0000] Failed to push manifest                       err="failed to put manifest registry.gitlab.com/francisferrell/http-ok:test: unauthorized" target="registry.gitlab.com/francisferrell/http-ok:test"
failed to put manifest registry.gitlab.com/francisferrell/http-ok:test: unauthorized
```

**Comment by francisferrell** [comment]
It also fails with 0.3.10

**Comment by sudo-bmitch** [comment]
I'm going to let #247 sit for a day to spend more time testing it and review the changes again. But I think it solves your issue and also handles the gitlab registry. Feel free to give it a try.

**Comment by francisferrell** [comment]
Hmmmm. The build fails.

```
#8 41.80 ++ git clone https://github.com/regclient/regclient.git
#8 41.80 Cloning into 'regclient'...
#8 42.28 ++ cd regclient
#8 42.28 ++ git checkout 7e78109bf677f3d0cb10ce1c93a76c53437c3052
#8 42.28 fatal: reference is not a tree: 7e78109bf677f3d0cb10ce1c93a76c53437c3052
```

**Comment by francisferrell** [comment]
Oh, I see. The commit is in a fork of this repo. I'm not accustomed to how things are done on Github with PRs.

It works! Both work, actually.

```
root@9c789c08236d:/# regctl version
{
  "VCSRef": "7e78109bf677f3d0cb10ce1c93a76c53437c3052",
  "VCSTag": ""
}
root@9c789c08236d:/# regctl image copy francisferrell/http-ok:latest francisferrell/http-ok:test
root@9c789c08236d:/# regctl image copy registry.gitlab.com/francisferrell/http-ok:750c36df registry.gitlab.com/francisferrell/http-ok:test
root@9c789c08236d:/# regctl image copy registry.gitlab.com/francisferrell/http-ok:750c36df francisferrell/http-ok:test
```

**Comment by sudo-bmitch** [comment]
Thanks for the follow up and all the debugging you did on your side. It was extremely helpful. The fix is merged into main so I'll close this. If you see anything else throwing errors, feel free to reach out.

On the PR checkout, Github has their CLI, but I tend to use the following shell script:

```
#!/bin/sh

if [ $# != 3 ]; then
  echo "usage: $0 [remote] [pr-num] [branch-name]" >&2
  exit 1
fi

set -ex
git fetch -fu "$1" "refs/pull/$2/head:$3"
git checkout "$3"
```

And then run it like `gh-pr origin 123 pr-123` to make or update the `pr-123` branch with pull request 123. Hope that can be useful.
